# -*- coding: utf-8 -*-
"""Copy of Review_IoT_Symmetry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGrRXgU9136sstd0Lq6uoaE5xN3tHb9E

# **IoT Symmetry Dataset:**


Question 1: Anomaly Detection

Question 2: Predict Smoke Levels

Question 3: Cluster Devices by Sensor Patterns

Question 4: Factors Influencing Motion Detection

Question 5: Predict Temperature based on Environment

For Dataset :[Link](https://docs.google.com/spreadsheets/d/1yaP5ik3tov0PeT3C-saDp7q1sjhKk2Lz0kDCtkPktAc/edit?usp=sharing)
"""

"Question 1: Anomaly Detection"

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest


df = pd.read_csv("/content/iot_telemetry_data - iot_telemetry_data.csv")

smoke = df


feature1 = 'temp'
feature2 = 'humidity'

X = smoke[[feature1, feature2]].dropna()


iso_forest = IsolationForest(contamination=0.01, random_state=42)
predictions = iso_forest.fit_predict(X)

plot_data = X.copy()
plot_data['anomaly'] = predictions


plt.figure(figsize=(10, 6))

plt.scatter(
    plot_data[plot_data['anomaly'] == 1][feature1],
    plot_data[plot_data['anomaly'] == 1][feature2],
    label='Normal (Inlier)'
)

plt.scatter(
    plot_data[plot_data['anomaly'] == -1][feature1],
    plot_data[plot_data['anomaly'] == -1][feature2],
    label='Anomaly (Outlier)'
)

plt.xlabel(feature1)
plt.ylabel(feature2)
plt.title('Isolation Forest Anomaly Detection Results')
plt.legend()
plt.show()

"Question 2: Predict Smoke Levels"

import pandas as pd
smoke = pd.read_csv("/content/iot_telemetry_data - iot_telemetry_data.csv")
smoke["ts"]=pd.to_datetime(smoke["ts"])

smoke.head()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
smoke["device"]=le.fit_transform(smoke["device"])
smoke["light"]=le.fit_transform(smoke["light"])
smoke["motion"]=le.fit_transform(smoke["motion"])

smoke.head()

columns=["device","co","humidity","light","temp"]
X = smoke[columns]
y= smoke["smoke"]

from  sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")
r2_score=r2_score(y_test, y_pred)
print(f"R2 Score: {r2_score}")

"Question 3: Cluster Devices by Sensor Patterns"

from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
smoke["device"]=le.fit_transform(smoke["device"])
smoke["light"]=le.fit_transform(smoke["light"])
smoke["motion"]=le.fit_transform(smoke["motion"])

columns=["smoke","co","humidity","light","temp"]
X = smoke[columns]
y= smoke["device"]
from  sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

knn_classifier.fit(X_train, y_train)
y_pred = knn_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

"Question 4: Factors Influencing Motion Detection"

smoke = pd.read_csv("/content/iot_telemetry_data - iot_telemetry_data.csv")

smoke["ts"]=pd.to_datetime(smoke["ts"]).astype('int64')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
smoke["device"]=le.fit_transform(smoke["device"])
smoke["light"]=le.fit_transform(smoke["light"])
smoke["motion"]=le.fit_transform(smoke["motion"])

columns=["ts","device","co","humidity","light","temp"]
X = smoke[columns]
y= smoke["motion"]

smoke.head()

from sklearn.linear_model import LogisticRegression
from  sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=LogisticRegression()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

"Question 5: Predict Temperature based on Environment"

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
smoke["device"]=le.fit_transform(smoke["device"])
smoke["light"]=le.fit_transform(smoke["light"])
smoke["motion"]=le.fit_transform(smoke["motion"])

columns=["humidity","light","motion","lpg","co"]
X = smoke[columns]
y= smoke["temp"]
from  sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeRegressor
model= DecisionTreeRegressor(max_depth=7, min_samples_leaf=20)
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_pred)
r2_score

from sklearn.tree import plot_tree

plt.figure(figsize=(18, 10))

plot_tree(
    model,
    feature_names=X.columns,
    filled=True
)

plt.tight_layout()

from sklearn.tree import DecisionTreeRegressor
model= DecisionTreeRegressor(max_depth=4, min_samples_leaf=16)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_pred)
r2_score

from sklearn.tree import plot_tree

plt.figure(figsize=(18, 10))

plot_tree(
    model,
    feature_names=X.columns,
    filled=True
)

plt.tight_layout()